version: '3'

services:
  node:
    hostname: node
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "1900"
    deploy:
        mode: replicated
        replicas: 16

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - node
      ports:
        - "1900:1900"

networks:
  default:
    driver: bridge
    name: containers